### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by xaviersand** [wirecloud-fiware/ngsi-source-operator#2]
On a fresh Wirecloud install, i follow your tutorial but as i get errors, i run these instead:
```https://github.com/wirecloud-fiware/ngsi-source-operator.
sudo apt-get install acct
sudo apt-get install curl
sudo apt-get install nodejs=0.6.12~dfsg1-1ubuntu1
sudo apt-get install nodejs-dev 
sudo apt-get install npm
curl -sL https://deb.nodesource.com/setup | sudo bash -
```
I noticed that we require not tu use the lastest version of nodejs, is this correct ? (otherwise i get errors)
But at the moment, the `npm` command does not seem to work.

Here is the log, you can see the npm error at the bottom
http://pastebin.com/DKcswxtR

**Comment by rockneurotiko** [comment]
Hi!

With the last nodejs install in ubuntu, npm is installed. Also, you are doing `npm install` in a a directory that is not the repository, `npm install` is executed to install the project dependencies.

This commands makes the project build correctly in a fresh ubuntu install:
``` bash
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install nodejs
sudo apt-get install git
git clone https://github.com/wirecloud-fiware/ngsi-source-operator.git
cd ngsi-source-operator
npm install
sudo npm install -g grunt-cli
grunt
```

**Comment by aarranz** [comment]
Hi xaviersand,

do you solve your problems? can we close this ticket?
