### ISSUE TITLE
Add support for multitenant context brokers (FIWARE-Service header)

### ISSUE THREAD

**Issue by justb4** [wirecloud-fiware/ngsi-source-operator#3]
This request comes from [StackOverflow](http://stackoverflow.com/questions/33452246/fiware-service-http-header-needed-for-orion-cb)

Basically, add a new preference for indicating what tenant is to be used for connecting to the context broker (if the preference is empty, then the FIWARE-Service header is not used).

See similar issue and fix here:  https://github.com/wirecloud-fiware/ngsi-browser-widget/issues/1

**Comment by justb4** [comment]
Ok, good to see, but I think the `config.xml` should also be updated to allow the user to set `ngsi_tenant`.

**Comment by aarranz** [comment]
Yeah, sorry, I pushed the changes by error. I've uploading also the commit adding the preference into the `config.xml`. I don't expect more problems, but I testing it just now, if everything goes well I will upload it into FIWARE Lab in a few minutes :).
