### ISSUE TITLE
npm install is failing on npm 3.10.10

### ISSUE THREAD

**Issue by pxds** [wirecloud-fiware/ngsi-source-operator#9]
I'm getting this error back:

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the libxmljs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs libxmljs
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls libxmljs
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     c:\projects\iot\health-iot\FIWARE\ngsi-source-operator\npm-debug.log

**Comment by aarranz** [comment]
Should be fixed by Wirecloud/node-wirecloud-config-parser#1, try to run `npm install` again 😃.
